export const siteLinks = {
  home: "/top",
  about: "/about",
  guide: "/guide",
  mix: "/mix",
  audioCheck: "/audio-check",
  works: "/works",
  instrumentals: "/instrumentals",
  compose: "/compose",

  googleForm: "https://forms.gle/srAnkjJyZLJVigmw8",
  googleFormCompose: "https://docs.google.com/forms/d/e/1FAIpQLSf_lT6dRVu3v6Xik3JupYa35X0rQZ-uD15rgpiGLEP1RtKk0g/viewform?usp=pp_url&entry.1511935247=%E4%BD%9C%E6%9B%B2%E4%BE%9D%E9%A0%BC%EF%BC%88%E6%96%99%E9%87%91%E3%81%AF%E7%9B%B8%E8%AB%87%EF%BC%89",
  youtubeChannel: "https://www.youtube.com/@iekaradenai_rin",
  youtubePlaylist: "https://www.youtube.com/playlist?list=PL9xTJo4NgKecdcBhJaL3MCZu9JBFjKG0h",
  niconico: "https://www.nicovideo.jp/user/47793022",
  piapro: "https://piapro.jp/iekaradenairin",
  x: "https://x.com/iekaradenai_Rin",
  domain: "https://iekaradenai.work",
  log: "/log",
} as const;
